version: '3.9'

services:

  app:
    container_name: aca_app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      - redis

  celery:
    container_name: aca_celery
    build:
      context: .
      dockerfile: dockerfile
    command: >
      celery -A tasks.celery_app worker
      -E --loglevel=INFO
      -Q new_emps,terminations,other
    volumes:
      - .:/code
    env_file: .env
    restart: unless-stopped
    depends_on:
      - redis

  flower:
    container_name: aca_flower
    build:
      context: .
      dockerfile: dockerfile
    command: >
      celery -A tasks.celery_app flower
      --basic_auth=admin:admin
    ports:
      - "5555:5555"
    volumes:
      - .:/code
    env_file: .env
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
