version: '3'
 
services:

  app:
    container_name: aca_app
    build: .
    ports:
      - "8000:8000"
    restart: "unless-stopped"
    volumes:
    - ./:/code
    env_file: .env
      
  celery:
    container_name: aca_celery
    build: ./services/celery
    volumes:
    - ./:/code
    command: celery -A tasks worker -E --loglevel=INFO -Q new_emps,terminations,other
    env_file: .env
    depends_on:
      - redis
    
  flower:
    container_name: aca_flower
    build: ./services/flower
    volumes:
    - ./:/code
    ports:
      - "5555:5555"
    command: celery -A tasks flower --basic_auth=admin:admin
    
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    volumes:
    - ./docker/volumes/redis:/data