FROM python:3.9-alpine

WORKDIR /code

COPY . /code

RUN pip install flower
RUN pip install celery
RUN pip install redis
RUN pip install boto3
RUN pip install asyncio
RUN pip install aiohttp
RUN pip install requests
RUN pip install environ
RUN pip install Jinja2